channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=21.2.3
- pip:
  - mlflow<3,>=2.2
  - argparse==1.4.0
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.4
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
