stages:
load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
       - src/get_data.py
       - src/load_data.py
       - Source_code/pokemon.csv
    outs:
       - data/raw/pokemon_course5i.csv

split_data:
      cmd: python src/split_data.py --config=params.yaml
      deps:
        - src/split_data.py
        - data/raw/pokemon_course5i.csv
      outs:
        - data/processed/train_pokemon_course5i.csv
        - data/processed/test_pokemon_course5i.csv

train_and_evaluate:
        cmd: python src/train_and_evaluate.py --config=params.yaml
        deps: 
          - data/Processed/train_pokemon_course5i.csv
          - data/Processed/test_pokemon_course5i.csv
          - src/train_and_evaluate.py

       Params:
           - estimators.LogisticRegression.Params.tol
           - estimators.LogisticRegression.Params.c
           - estimators.LogisticRegression.Params.max_iter



       metrics:
          - reports/Scores.json
          cache: false
          - reports/Params.json
          cache: false

       outs:
         -models/model.joblib
#log_production_model:

 #  cmd: python src/log_production_model.py --config=params.yaml

  # deps:

    #- src/log_production_model.py
